version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app         # Mount your code (live changes)
      - /app/node_modules  # Avoid overwriting node_modules
    env_file:
      - .env
    command: ["npm", "run", "dev"]
